# Generated by Django 5.0.1 on 2024-02-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_products_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
